DLR-SC/ESID

frontend/src/components/Sidebar/DistrictMap.tsx

The highlight district effect should probably not look exactly like hovering a district.

:tada: Adds district highlighting

---

.github/workflows/push.yml
frontend/package-lock.json
frontend/src/components/IconBar.tsx
frontend/src/components/Sidebar/DistrictMap.tsx

Adds a play button, which progresses the time by a day a second. It also delays showing the loading indicator on the map by one second.
closes #86

Add play feature.

---

frontend/public/locales/de/global.json5
frontend/public/locales/en/global.json5
frontend/src/components/Scenario.tsx
frontend/src/components/SimulationChart.tsx
frontend/src/store/index.ts
frontend/src/store/services/caseDataApi.ts
frontend/src/types/caseData.ts

This renames all rki mentions in the frontend. The only exception is here: https://github.com/DLR-SC/ESID/blob/fb64e7eb69fdc2368ab4aad0212e05678b29a95f/frontend/src/store/services/caseDataApi.ts#L7
We need the API to change the endpoint first.
Resolves #175

Rename RKI data to case data.

---

frontend/package-lock.json
frontend/src/components/ScenarioCard.tsx

Moved the logic to select the proper trend arrow glyph to a function to avoid drawing multiple glyphs.
Removed unnecessary DOM-Elements from react component, the function olny returns one element.

moved scenario card arrows to function

---

.github/ISSUE_TEMPLATE/BUG-REPORT.yml
.github/ISSUE_TEMPLATE/FEEDBACK-REPORT.yml

Adds forms to create new feedback and bug reports.
I, the author of this PR checked the following requirements for good software quality:
- ~~The code is written with our software quality standards (I ran the linter)~~
- ~~The code is written using our code style~~
- ~~Extensive in source documentation has been added~~
- ~~Unit and/or integration tests have been added~~
- ~~I tried addressing all new accessibility problems displayed in the console and documented if they can't be fixed~~
- ~~I attached performance measurements to prevent performance degradation~~
I, the reviewer checked the following things:
- ~~I ran the software once and tried all new and related functionality to this PR~~
- ~~I read the added documentation and checked if it is understandable and clear~~
- ~~I checked …

:tada: Add Issue Forms

---

.github/ISSUE_TEMPLATE/BUG-REPORT.yml
.github/ISSUE_TEMPLATE/FEEDBACK-REPORT.yml
.github/pull_request_template.md
README.md
docs/changelog.md
frontend/README.md

This adds a changelog to our doc folder to record the changes made over time.
It also adds a check to the pull request template to remind submitters to add their changes to the log.
I, the author of this PR checked the following requirements for good software quality:
I, the reviewer checked the following things:

Add changelog

---

docs/changelog.md
frontend/src/components/ManageGroupDialog.tsx
frontend/src/store/DataSelectionSlice.ts

This fixes a crash when a user loads the site, who has an old cache.
None

:beetle: Fix group filter update issue.

---

docs/changelog.md
frontend/src/components/Sidebar/DistrictMap.tsx

This PR re-enables selected district highlighting.
This resolves #201.

:beetle: Revert selected district highlighting

---

docs/changelog.md
frontend/public/locales/de/global.json5
frontend/public/locales/en/global.json5
frontend/src/components/Scenario.tsx

Added a label to the start day in the scenario component.
Resolves #202

Add description to start day.

---

docs/changelog/changelog-de.md
docs/changelog/changelog-en.md
frontend/public/locales/de/global.json5
frontend/public/locales/en/global.json5
frontend/src/components/ManageGroupDialog.tsx
frontend/src/components/Scenario.tsx

… changes.
This adds a confirmation dialog to the group filter editor that requires users to confirm if they want to discard changes.
Closes #209 

The group filter editor now prevents accidentally discarding changes.

---

.github/ISSUE_TEMPLATE/EPIC.yml

Adds a template to create an epic with all the information and steps needed.

:scroll: Add Issue Template for Epics

---

.github/ISSUE_TEMPLATE/EPIC.yml

this aims to fix the issues with the issue template.

🔧 Merge org/epic issue template

---

frontend/tools/CollectAttributions.ts

Fixes a lint error in the CollectAttributions script.

Fix collect attributions lint error.

---

frontend/docs/changelog/changelog-de.md
frontend/docs/changelog/changelog-en.md
frontend/public/locales/de/backend.json5
frontend/public/locales/en/backend.json5
frontend/src/components/Scenario/CompartmentList.tsx

Adds a small info button to each infection state. They all containe the same text for now.

Infection State Info

---

frontend/docs/changelog/changelog-de.md
frontend/docs/changelog/changelog-en.md
frontend/src/components/Scenario/CompartmentList.tsx
frontend/src/util/Theme.ts

Some small adjustments to tooltips.

Tooltip Refinements

---

frontend/docs/changelog/changelog-de.md
frontend/docs/changelog/changelog-en.md
frontend/public/locales/de/backend.json5
frontend/public/locales/de/global.json5
frontend/public/locales/en/backend.json5
frontend/public/locales/en/global.json5
frontend/src/__tests__/store/DataSelectionSlice.test.ts
frontend/src/components/Scenario/CompartmentList.tsx
frontend/src/components/Scenario/index.tsx
frontend/src/store/DataSelectionSlice.ts
frontend/src/store/ScenarioSlice.ts

Add translation for 'Mild Infections' and also disable the "more" button if only 4 compartments exist.

More Infection State Translations

---

frontend/docs/changelog/changelog-de.md
frontend/docs/changelog/changelog-en.md
frontend/src/components/Scenario/hooks.ts

Fixed a bug, that crashed the website, because of a cached start date.

Fix invalid start date cache

---

.github/workflows/push.yml

Add gitleaks check to CI.

---

.gitignore
frontend/.gitignore

Add the dist folder to .gitignore, as vite puts output there.

:wrench: Ignore dist folder.

---

frontend/Dockerfile

Update the version of the docker container to use node 20.

:wrench: Update node version in Dockerfile.

---

frontend/vite.config.mts

Fix vite not generating relative paths.

Fix vite config to generated relative paths.

---

frontend/docs/changelog/changelog-de.md
frontend/docs/changelog/changelog-en.md
frontend/locales/de-backend.json5
frontend/locales/en-backend.json5

Add translations for the baseline scenario.

Add translations for the baseline scenario.

---

frontend/src/util/Theme.ts

It moves the second scenario color (purple) to the back or the list to reduce confusion with the main ui color (also purple).

reorder scenarios

---

backend/src/api/management/commands/import_simulation.py

add all days to simulation upload

---

frontend/assets/pandemos/.gitignore
frontend/package-lock.json
frontend/package.json
frontend/src/App.tsx
frontend/src/components/LineChartContainer.tsx
frontend/src/components/ScenarioComponents/ScenarioContainer.tsx
frontend/src/components/Sidebar/SidebarContainer.tsx
frontend/src/data_sockets/DataContext.tsx
frontend/src/data_sockets/PandemosContext.tsx

This adds a new Datasocket to the app to provide the Pandemos sample dataset.
For the datasocket to work you need to have the json files in the `frontend/assets/pandemos` folder.
The data in on the internal shared drive (`VR_DATA/Mobility/PANDEMOS/Datasocket data`).

add pandemos data socket
